"""
report_generators.py — PDF and Excel generation for HoneyPrompt Sentinel reports.
"""
import io
from datetime import datetime


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _fmt(v, default="—"):
    if v is None:
        return default
    return str(v)


def _pct(v):
    if v is None:
        return "—"
    try:
        return f"{float(v) * 100:.1f}%"
    except Exception:
        return str(v)


def _date(ts):
    if not ts:
        return "—"
    try:
        return datetime.fromisoformat(ts).strftime("%Y-%m-%d %H:%M")
    except Exception:
        return str(ts)


# ---------------------------------------------------------------------------
# PDF Generation
# ---------------------------------------------------------------------------

def generate_pdf(report_type: str, data: dict, generated_by: str, filters: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm,
        topMargin=20*mm, bottomMargin=20*mm,
    )

    styles = getSampleStyleSheet()
    GOLD = colors.HexColor("#f59e0b")
    RED = colors.HexColor("#ef4444")
    GREEN = colors.HexColor("#10b981")
    DARK = colors.HexColor("#0f172a")
    GRAY = colors.HexColor("#64748b")
    WHITE = colors.white

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=18, textColor=GOLD, spaceAfter=4)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=9, textColor=GRAY, spaceAfter=2)
    h2_style = ParagraphStyle("h2", parent=styles["Heading2"],
        fontSize=11, textColor=GOLD, spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle("body", parent=styles["Normal"],
        fontSize=8, textColor=colors.HexColor("#e2e8f0"), spaceAfter=3)
    conf_style = ParagraphStyle("conf", parent=styles["Normal"],
        fontSize=7, textColor=RED, spaceAfter=2)

    def tbl(headers, rows, col_widths=None):
        tdata = [headers] + (rows if rows else [["—"] * len(headers)])
        t = Table(tdata, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), GOLD),
            ("FONTSIZE", (0, 0), (-1, 0), 7),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (-1, -1), 7),
            ("TEXTCOLOR", (0, 1), (-1, -1), colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.HexColor("#1e293b"), colors.HexColor("#0f172a")]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#334155")),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        return t

    story = []

    # Header
    story.append(Paragraph("🐝 HoneyPrompt Sentinel", title_style))
    story.append(Paragraph(f"SECURITY REPORT — {report_type.upper().replace('_', ' ')}", sub_style))
    story.append(Paragraph(f"Generated by: {generated_by}  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", sub_style))

    filter_parts = []
    if filters.get("date_from"):
        filter_parts.append(f"From: {filters['date_from']}")
    if filters.get("date_to"):
        filter_parts.append(f"To: {filters['date_to']}")
    for k in ("classification", "severity", "threat_type", "action", "status"):
        if filters.get(k) and filters[k].upper() not in ("ALL", ""):
            filter_parts.append(f"{k.title()}: {filters[k]}")
    if filter_parts:
        story.append(Paragraph("Filters: " + "  |  ".join(filter_parts), sub_style))

    story.append(Paragraph("CONFIDENTIAL — SECURITY REPORT", conf_style))
    story.append(HRFlowable(width="100%", thickness=1, color=GOLD, spaceAfter=10))

    # ---- Content by report type ----
    if report_type == "security_overview":
        story.append(Paragraph("Security Overview", h2_style))
        s = data.get("summary", {})
        rows = [
            ["Total Users", _fmt(s.get("total_users")), "Active Users", _fmt(s.get("active_users"))],
            ["Inactive Users", _fmt(s.get("inactive_users")), "Blocked Users", _fmt(s.get("blocked_users"))],
            ["Total Prompts", _fmt(s.get("total_prompts")), "Safe Prompts", _fmt(s.get("safe"))],
            ["Suspicious", _fmt(s.get("suspicious")), "Malicious", _fmt(s.get("malicious"))],
            ["Blocked", _fmt(s.get("blocked")), "Block Rate", _pct(s.get("block_rate"))],
            ["Critical Threats", _fmt(s.get("critical")), "High Severity", _fmt(s.get("high"))],
        ]
        story.append(tbl(["Metric", "Value", "Metric", "Value"], rows))

        if data.get("threat_by_type"):
            story.append(Paragraph("Threat Distribution by Type", h2_style))
            rows2 = [[k, str(v)] for k, v in sorted(data["threat_by_type"].items(), key=lambda x: -x[1])]
            story.append(tbl(["Threat Type", "Count"], rows2))

        if data.get("severity_dist"):
            story.append(Paragraph("Severity Distribution", h2_style))
            rows3 = [[k, str(v)] for k, v in data["severity_dist"].items()]
            story.append(tbl(["Severity", "Count"], rows3))

    elif report_type == "threat_intelligence":
        story.append(Paragraph("Threat Intelligence", h2_style))
        items = data.get("threats", [])
        rows = [[
            _fmt(r.get("threat_type")), _fmt(r.get("count")),
            _fmt(r.get("severity")), _pct(r.get("avg_confidence")),
        ] for r in items]
        story.append(tbl(["Threat Type", "Count", "Severity", "Avg Confidence"], rows))

        if data.get("top_users"):
            story.append(Paragraph("Most Targeted Users", h2_style))
            rows2 = [[u, str(c)] for u, c in data["top_users"].items()]
            story.append(tbl(["Username", "Attack Count"], rows2))

    elif report_type == "user_security":
        story.append(Paragraph("User Security Report", h2_style))
        items = data.get("users", [])
        rows = [[
            _fmt(r.get("username")), _fmt(r.get("email")),
            _fmt(r.get("status")), _fmt(r.get("total_prompts")),
            _fmt(r.get("malicious")), _fmt(r.get("risk_score")),
        ] for r in items]
        story.append(tbl(
            ["Username", "Email", "Status", "Total", "Malicious", "Risk"],
            rows,
        ))

    elif report_type == "audit_log":
        story.append(Paragraph("Audit Log Report", h2_style))
        items = data.get("logs", [])
        rows = [[
            _date(r.get("timestamp")), _fmt(r.get("admin")),
            _fmt(r.get("action")), _fmt(r.get("target")),
            _fmt(r.get("reason", ""))[:40],
        ] for r in items]
        story.append(tbl(["Timestamp", "Admin", "Action", "Target", "Reason"], rows))

    elif report_type == "incidents":
        story.append(Paragraph("Incident Report", h2_style))
        items = data.get("incidents", [])
        rows = [[
            _fmt(r.get("incident_id")), _date(r.get("created_at")),
            _fmt(r.get("title", ""))[:30], _fmt(r.get("severity")),
            _fmt(r.get("status")), _fmt(r.get("created_by")),
        ] for r in items]
        story.append(tbl(["ID", "Created", "Title", "Severity", "Status", "Admin"], rows))

    elif report_type == "chat_activity":
        story.append(Paragraph("Chat & Security Activity", h2_style))
        s = data.get("summary", {})
        rows = [
            ["Total Conversations", _fmt(s.get("total_conversations"))],
            ["Total Messages", _fmt(s.get("total_messages"))],
            ["Threat Detections", _fmt(s.get("threat_detections"))],
            ["Blocked Messages", _fmt(s.get("blocked_messages"))],
            ["Suspicious Messages", _fmt(s.get("suspicious_messages"))],
        ]
        story.append(tbl(["Metric", "Value"], rows))

    # User reports
    elif report_type == "personal_security":
        story.append(Paragraph("Personal Security Report", h2_style))
        s = data.get("summary", {})
        rows = [
            ["Username", _fmt(s.get("username")), "Status", _fmt(s.get("status"))],
            ["Total Prompts", _fmt(s.get("total_prompts")), "Safe", _fmt(s.get("safe"))],
            ["Suspicious", _fmt(s.get("suspicious")), "Malicious", _fmt(s.get("malicious"))],
            ["Blocked", _fmt(s.get("blocked")), "Risk Score", _fmt(s.get("risk_score"))],
        ]
        story.append(tbl(["Metric", "Value", "Metric", "Value"], rows))

    elif report_type == "security_history":
        story.append(Paragraph("Security History", h2_style))
        items = data.get("history", [])
        rows = [[
            _date(r.get("timestamp")), _fmt(r.get("prompt_preview", ""))[:35],
            _fmt(r.get("classification")), _fmt(r.get("threat_type")),
            _fmt(r.get("severity")), _fmt(r.get("action")),
        ] for r in items]
        story.append(tbl(["Time", "Prompt Preview", "Class", "Threat", "Severity", "Action"], rows))

    elif report_type == "my_chat_activity":
        story.append(Paragraph("My Chat Activity", h2_style))
        s = data.get("summary", {})
        rows = [
            ["Conversations", _fmt(s.get("total_conversations"))],
            ["Messages", _fmt(s.get("total_messages"))],
            ["Threat Detections", _fmt(s.get("threat_detections"))],
            ["Blocked Messages", _fmt(s.get("blocked_messages"))],
        ]
        story.append(tbl(["Metric", "Value"], rows))

    elif report_type == "security_alerts":
        story.append(Paragraph("Security Alerts", h2_style))
        items = data.get("alerts", [])
        rows = [[
            _date(r.get("timestamp")), _fmt(r.get("threat_type")),
            _fmt(r.get("severity")), _fmt(r.get("classification")),
            _fmt(r.get("action")),
        ] for r in items]
        story.append(tbl(["Time", "Threat Type", "Severity", "Classification", "Action"], rows))

    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY))
    story.append(Paragraph(
        f"HoneyPrompt Sentinel — Confidential Security Report — Generated {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=6, textColor=GRAY, alignment=1)
    ))

    doc.build(story)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Excel Generation
# ---------------------------------------------------------------------------

def generate_excel(report_type: str, data: dict, generated_by: str, filters: dict) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    wb = Workbook()

    GOLD = "F59E0B"
    DARK = "0F172A"
    MID = "1E293B"
    WHITE = "FFFFFF"
    RED = "EF4444"
    GREEN = "10B981"

    def hdr_font():
        return Font(bold=True, color=WHITE, size=9)

    def hdr_fill():
        return PatternFill("solid", fgColor=DARK)

    def gold_font():
        return Font(bold=True, color=GOLD, size=10)

    def thin_border():
        s = Side(style="thin", color="334155")
        return Border(left=s, right=s, top=s, bottom=s)

    def write_sheet(ws, title, headers, rows):
        ws.title = title
        ws.sheet_properties.tabColor = GOLD
        # Title row
        ws.append([f"HoneyPrompt Sentinel — {title}"])
        ws.append([f"Generated by: {generated_by}  |  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"])
        ws.append([])
        # Headers
        ws.append(headers)
        for col_idx, _ in enumerate(headers, 1):
            cell = ws.cell(row=4, column=col_idx)
            cell.font = hdr_font()
            cell.fill = hdr_fill()
            cell.alignment = Alignment(horizontal="center")
            cell.border = thin_border()
        # Data
        for row in rows:
            ws.append([str(v) if v is not None else "" for v in row])
        # Column widths
        for col_idx in range(1, len(headers) + 1):
            col_letter = get_column_letter(col_idx)
            max_len = max(
                (len(str(ws.cell(row=r, column=col_idx).value or "")) for r in range(4, ws.max_row + 1)),
                default=10
            )
            ws.column_dimensions[col_letter].width = min(max(max_len + 2, 12), 45)
        # Title styling
        ws["A1"].font = gold_font()
        ws["A2"].font = Font(color="94A3B8", size=8)

    # ---- Summary sheet ----
    ws_sum = wb.active
    summary_rows = []

    if report_type in ("security_overview", "personal_security"):
        s = data.get("summary", {})
        for k, v in s.items():
            summary_rows.append([k.replace("_", " ").title(), _fmt(v)])
        write_sheet(ws_sum, "Summary", ["Metric", "Value"], summary_rows)
    else:
        write_sheet(ws_sum, "Summary", ["Report", "Generated At", "Generated By"],
                    [[report_type, datetime.now().isoformat(), generated_by]])

    # ---- Type-specific sheets ----
    if report_type == "security_overview":
        # Users sheet
        ws_u = wb.create_sheet("Users")
        users = data.get("users", [])
        write_sheet(ws_u, "Users", ["Username", "Email", "Status", "Total", "Safe", "Suspicious", "Malicious", "Blocked", "Risk Score"],
            [[r.get("username"), r.get("email"), r.get("status"), r.get("total_prompts"),
              r.get("safe"), r.get("suspicious"), r.get("malicious"), r.get("blocked"), r.get("risk_score")]
             for r in users])

        # Threats sheet
        ws_t = wb.create_sheet("Threats")
        write_sheet(ws_t, "Threats", ["Threat Type", "Count"],
            [[k, v] for k, v in (data.get("threat_by_type") or {}).items()])

        # Severity sheet
        ws_s = wb.create_sheet("Severity")
        write_sheet(ws_s, "Severity", ["Severity", "Count"],
            [[k, v] for k, v in (data.get("severity_dist") or {}).items()])

    elif report_type == "threat_intelligence":
        ws_t = wb.create_sheet("Threats")
        write_sheet(ws_t, "Threats",
            ["Threat Type", "Count", "Severity", "Avg Confidence"],
            [[r.get("threat_type"), r.get("count"), r.get("severity"), _pct(r.get("avg_confidence"))]
             for r in data.get("threats", [])])

        ws_u = wb.create_sheet("Top Users")
        write_sheet(ws_u, "Top Users", ["Username", "Attack Count"],
            [[u, c] for u, c in (data.get("top_users") or {}).items()])

    elif report_type == "user_security":
        ws_u = wb.create_sheet("Users")
        write_sheet(ws_u, "Users",
            ["Username", "Email", "Status", "Total", "Safe", "Suspicious", "Malicious", "Blocked", "Risk Score", "Last Activity"],
            [[r.get("username"), r.get("email"), r.get("status"), r.get("total_prompts"),
              r.get("safe"), r.get("suspicious"), r.get("malicious"), r.get("blocked"),
              r.get("risk_score"), _date(r.get("last_activity"))]
             for r in data.get("users", [])])

    elif report_type == "audit_log":
        ws_a = wb.create_sheet("Audit Logs")
        write_sheet(ws_a, "Audit Logs",
            ["Timestamp", "Admin", "Action", "Target", "Reason"],
            [[_date(r.get("timestamp")), r.get("admin"), r.get("action"),
              r.get("target"), r.get("reason")]
             for r in data.get("logs", [])])

    elif report_type == "incidents":
        ws_i = wb.create_sheet("Incidents")
        write_sheet(ws_i, "Incidents",
            ["Incident ID", "Created", "Title", "Severity", "Status", "Admin", "Resolved At"],
            [[r.get("incident_id"), _date(r.get("created_at")), r.get("title"),
              r.get("severity"), r.get("status"), r.get("created_by"), _date(r.get("resolved_at"))]
             for r in data.get("incidents", [])])

    elif report_type == "chat_activity":
        ws_c = wb.create_sheet("Activity")
        s = data.get("summary", {})
        write_sheet(ws_c, "Activity", ["Metric", "Value"],
            [[k.replace("_", " ").title(), v] for k, v in s.items()])

    elif report_type == "personal_security":
        ws_h = wb.create_sheet("Security History")
        write_sheet(ws_h, "Security History",
            ["Timestamp", "Prompt Preview", "Classification", "Threat Type", "Severity", "Confidence", "Action"],
            [[_date(r.get("timestamp")), r.get("prompt_preview"), r.get("classification"),
              r.get("threat_type"), r.get("severity"), _pct(r.get("confidence")), r.get("action")]
             for r in data.get("history", [])])

    elif report_type == "security_history":
        ws_h = wb.create_sheet("Security History")
        write_sheet(ws_h, "Security History",
            ["Timestamp", "Prompt Preview", "Classification", "Threat Type", "Severity", "Confidence", "Action", "Reason"],
            [[_date(r.get("timestamp")), r.get("prompt_preview"), r.get("classification"),
              r.get("threat_type"), r.get("severity"), _pct(r.get("confidence")),
              r.get("action"), r.get("reason")]
             for r in data.get("history", [])])

    elif report_type == "my_chat_activity":
        ws_c = wb.create_sheet("Chat Activity")
        s = data.get("summary", {})
        write_sheet(ws_c, "Chat Activity", ["Metric", "Value"],
            [[k.replace("_", " ").title(), v] for k, v in s.items()])

    elif report_type == "security_alerts":
        ws_a = wb.create_sheet("Alerts")
        write_sheet(ws_a, "Alerts",
            ["Timestamp", "Threat Type", "Severity", "Classification", "Action", "Reason"],
            [[_date(r.get("timestamp")), r.get("threat_type"), r.get("severity"),
              r.get("classification"), r.get("action"), r.get("reason")]
             for r in data.get("alerts", [])])

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
